ApptecPortalWeb/Models/DegreeModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ApptecPortalWeb.Models
{
    public class DegreeModel
    {
        public string Nombre { get; set; }
    }
}

ApptecPortalWeb/Controllers/CareersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ApptecPortalWeb.Controllers
{
    public class CareersController : Controller
    {
        // GET: Careers
        public ActionResult CreateCareer()
        {
            return View();
        }

        public ActionResult UpdateCareer()
        {
            return View();
        }

        public ActionResult ShowCareer()
        {
            return View();
        }
    }
}

ApptecPortalWeb/Controllers/ClaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ApptecPortalWeb.Controllers
{
    public class ClaseController : Controller
    {
        // GET: Clase
        public ActionResult CreateClase()
        {
            return View();
        }

        public ActionResult UpdateClase()
        {
            return View();
        }

        public ActionResult ShowClase()
        {
            return View();
        }
    }
}

ApptecPortalWeb/Controllers/ClassDegreeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ApptecPortalWeb.Controllers
{
    public class ClassDegreeController : Controller
    {
        // GET: ClassDegree
        public ActionResult CreateClassDegree()
        {
            return View();
        }

        public ActionResult UpdateClassDegree()
        {
            return View();
        }

        public ActionResult ShowClassDegree()
        {
            return View();
        }
    }
}

ApptecPortalWeb/Controllers/ClassroomsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ApptecPortalWeb.Controllers
{
    public class ClassroomsController : Controller
    {
        // GET: Classrooms
        public ActionResult CreateClassroom()
        {
            return View();
        }

        public ActionResult UpdateClassroom()
        {
            return View();
        }

        public ActionResult ShowClassroom()
        {
            return View();
        }
    }
}

ApptecPortalWeb/Controllers/DegreeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ApptecPortalWeb.Controllers
{
    public class DegreeController : Controller
    {
        // GET: Degree
        public ActionResult CreateDegree()
        {
            return View();
        }

        public ActionResult UpdateDegree()
        {
            return View();
        }


        public ActionResult ShowDegree()
        {
            return View();
        }
    }
}

ApptecPortalWeb/Controllers/EmployerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ApptecPortalWeb.Controllers
{
    public class EmployerController : Controller
    {
        // GET: Employer
        public ActionResult CreateEmployer()
        {
            return View();
        }

        public ActionResult UpdateEmployer()
        {
            return View();
        }

        public ActionResult ShowEmployer()
        {
            return View();
        }
    }
}

ApptecPortalWeb/Controllers/GroupsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ApptecPortalWeb.Controllers
{
    public class GroupsController : Controller
    {
        // GET: Groups
        public ActionResult CreateGroup()
        {
            return View();
        }
        public ActionResult UpdateGroup()
        {
            return View();
        }

        public ActionResult ShowGroup()
        {
            return View();
        }
    }
}

ApptecPortalWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ApptecPortalWeb.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Inicio()
        {
            return View();
        }
    }
}

ApptecPortalWeb/Controllers/InstitutionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ApptecPortalWeb.Controllers
{
    public class InstitutionsController : Controller
    {
        // GET: Institutions
        public ActionResult CreateInstitution()
        {
            return View();
        }

        public ActionResult ShowInstitution()
        {
            return View();
        }
    }
}

ApptecPortalWeb/Controllers/InstitutoRegisterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ApptecPortalWeb.Controllers
{
    public class InstitutoRegisterController : Controller
    {
        public ActionResult RegisterInstituto()
        {
            return View();
        }
    }
}

ApptecPortalWeb/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ApptecPortalWeb.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Login()
        {
            return View();
        }
    }
}

ApptecPortalWeb/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ApptecPortalWeb.Controllers
{
    public class ProfileController : Controller
    {
        // GET: Profile
        public ActionResult CreateProfile()
        {
            return View();
        }

        public ActionResult ShowProfile()
        {
            return View();
        }

        public ActionResult ShowAdmins()
        {
            return View();

        }
    }
}

ApptecPortalWeb/Controllers/SpecialityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ApptecPortalWeb.Controllers
{
    public class SpecialityController : Controller
    {
        // GET: Speciality
        public ActionResult CreateSpeciality()
        {
            return View();
        }

        public ActionResult UpdateSpeciality()
        {
            return View();
        }

        public ActionResult ShowSpeciality()
        {
            return View();
        }
    }
}

ApptecPortalWeb/Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ApptecPortalWeb.Controllers
{
    public class StudentsController : Controller
    {
        // GET: Students
        public ActionResult CreateStudent()
        {
            return View();
        }

        public ActionResult UpdateStudent()
        {
            return View();
        }

        public ActionResult ShowStudent()
        {
            return View();
        }

    }
}

ApptecPortalWeb/Controllers/SubjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ApptecPortalWeb.Controllers
{
    public class SubjectsController : Controller
    {
        // GET: Subjects
        public ActionResult CreateSubject()
        {
            return View();
        }

        public ActionResult UpdateSubject()
        {
            return View();
        }

        public ActionResult showSubject()
        {
            return View();
        }
    }
}

ApptecPortalWeb/Views/ClassDegree/CreateClassDegree.cshtml
@{
    ViewBag.Title = "Materia y grado";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="main-panel">
    <div class="content-wrapper">
        <div class="row">
            <div class="col-md-12">
                <div class="row flex-grow">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                <h4 class="card-title">Asignación de materias y grados educativos</h4>
                                <div class="card">
                                    <div class="card-body">
                                        <form id="form" method="post">
                                            <div class="row">
                                                <div class="col-md-6">
                                                    <div class="form-group">
                                                        <label>Materia</label>
                                                        <select class="form-control" id="materiaId" autocomplete="on" required>
                                                            <option selected>Seleccionar</option>
                                                        </select>
                                                    </div>
                                                </div>
                                                <div class="col-md-6">
                                                    <div class="form-group">
                                                        <label>Grado</label>
                                                        <select class="form-control" id="gradoId" autocomplete="on" required>
                                                            <option default> Seleccionar</option>
                                                        </select>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-md-2"></div>
                                                <div class="col-md-2"></div>
                                                <div class="col-md-2"></div>
                                                <div class="col-md-2"></div>
                                                <div class="col-md-2">
                                                </div>
                                                <div class="col-md-2">
                                                    <br><br>
                                                    <button type="button" id="saveSubjectDegree" class="btn btn-success mr-2">Guardar</button>
                                                </div>
                                            </div>
                                         </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>


        <script type="text/javascript" src="~/Scripts/jquery-3.4.1.js"></script>
        <script src="~/Scripts/Platform/DegreeSubject/GetDegree.js"></script>
        <script src="~/Scripts/Platform/DegreeSubject/CreateDegreeSubject.js"></script>

ApptecPortalWeb/Views/ClassDegree/ShowClassDegree.cshtml
@{
    ViewBag.Title = "Mostrar materias y grados";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="main-panel">
    <div class="content-wrapper">
        <div class="row">
            <div class="col-md-12">
                <div class="row flex-grow">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                <h4 class="card-title">Asignaci&oacute;n de maerias y grados registrados </h4>
                                <div class="card">
                                    <div class="card-body">
                                        <form class="forms-sample">
                                            <table id="degreeSubject" class="table table-striped table-bordered" style="width:100%">
                                                <thead>
                                                    <tr>
                                                        <th>Materia</th>
                                                        <th>Grado</th>
                                                        <th>Opciones</th>
                                                    </tr>
                                                </thead>
                                            </table>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
 

<script type="text/javascript" src="~/Scripts/jquery-3.4.1.js"></script>
<script src="~/Scripts/Platform/DegreeSubject/ShowDegreeSubject.js"></script>

ApptecPortalWeb/Views/Classrooms/ShowClassroom.cshtml
@{
    ViewBag.Title = "Mostrar aulas";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="main-panel">
    <div class="content-wrapper">
        <div class="row">
            <div class="col-md-12">
                <div class="row flex-grow">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                <h4 class="card-title">Aulas registradas</h4>
                                <div class="card">
                                    <div class="card-body">
                                        <form class="forms-sample">
                                            <table id="classroom" class="table table-striped table-bordered" style="width:100%">
                                                <thead>
                                                    <tr>
                                                        <th>Clave</th>
                                                        <th>Nombre</th>
                                                        <th>Descripci&oacute;n</th>
                                                        <th>Instituci&oacute;n</th>
                                                        <th>Tipo aula</th>
                                                        <th>Opciones</th>
                                                    </tr>
                                                </thead>
                                            </table>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
 

<script type="text/javascript" src="~/Scripts/jquery-3.4.1.js"></script>
<script type="text/javascript" src="~/Scripts/Platform/Classrroom/ShowClassroom.js"></script>

ApptecPortalWeb/Views/Home/Inicio.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

ApptecPortalWeb/Views/Institutions/CreateInstitution.cshtml
@{
    ViewBag.Title = "Institucion educativa";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="main-panel">
    <div class="content-wrapper">
        <div class="row">
            <div class="col-md-12 d-flex align-items-stretch grid-margin">
                <div class="row flex-grow">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                <h4 class="card-title">Instituci&oacute;n educativa</h4>
                                <div class="card">
                                    <div class="card-body">
                                        @using (Html.BeginForm("CreateInstitution", "Institutions", FormMethod.Post))
                                        {
                                            <div class="row">
                                                <div class="col-md-6">
                                                    <div class="form-group">
                                                        <label>Nombre instituci&oacute;n</label>
                                                        <input type="text" class="form-control" id="nombreInstitucion" placeholder="Nombre" value="" disabled>
                                                    </div>
                                                </div>
                                                <div class="col-md-6">
                                                    <div class="form-group">
                                                        <label>Direcci&oacute;n</label>
                                                        <input type="text" class="form-control" id="direccionInstitucion" placeholder="Dirección" value="" required>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-md-6">
                                                    <div class="form-group">
                                                        <label>Tel&eacute;fono</label>
                                                        <input type="text" class="form-control" id="telefonoInstitucion" placeholder="Teléfono" value="" required>
                                                    </div>
                                                </div>
                                                <div class="col-md-6">
                                                    <div class="form-group">
                                                        <label>Nivel educativo</label>
                                                        <select class="form-control" id="nivelEdInstitucion" required>
                                                            <option selected>Seleccionar</option>

                                                        </select>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <label>Director</label>
                                                <div class="col-md-6">
                                                    <div class="form-group">
                                                        <input type="text" class="form-control" id="directorInstitucion" placeholder="Nombre completo del director" value="" required>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-md-2"></div>
                                                <div class="col-md-2"></div>
                                                <div class="col-md-2"></div>
                                                <div class="col-md-2"></div>
                                                <div class="col-md-2">
                                                </div>
                                                <div class="col-md-2">
                                                    <br><br>
                                                    <button type="button" onclick="actualizar()" class="btn btn-success mr-2">Actualizar</button>
                                                </div>
                                            </div>
                                        }
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>


        <script>

            var accion;
            var error;
            var msj;

                $(document).ready(function () {
                    LoadEducationLevel();
                });

                var valor;

                var dateuser = localStorage.getItem("keyuser");
                alert("usuario: " + dateuser);

                function LoadEducationLevel() {
                    $.ajax({
                        url: "http://localhost:59538/Api/Institution/ShowEducationLevel",
                        method: "POST",
                        dataType: "json",
                        data: "{}",
                        success: function (data) {

                            for (var i = 0; i < data.length; i++) {
                                console.log(data[i].id);
                                $("#nivelEdInstitucion").append("<option value=" + data[i].id + ">" + data[i].nombre + "</option>");
                            }


                        },
                        error: function (jqXHR, status, error) {
                            alert('Disculpe, existió un problema');
                        }
                    });
                }


                var id = @Request.QueryString["id"];

                //alert(id);




                var nombre = $("#nombreInstitucion").val();
                var direccion = $("#direccionInstitucion").val();
                var telefono = $("#telefonoInstitucion").val();
                var nivel = $("#nivelEdInstitucion").val();
                var director = $("#directorInstitucion").val();


                var oModel = {


                    "institutionID": id


                }

                $.ajax({

                    "async": true,
                    "crossDomain": true,
                    "cache": false,
                    "method": "POST",
                    "url": "http://localhost:59538/Api/Institution/UpdateShow",
                    "data": JSON.stringify(oModel),
                    "contentType": "application/json"


                }).done(function (data) {


                    console.log(data);

                    for (var i = 0, len = data.length; i < len; i++) {
                        localStorage.setItem("inst", data[i].institutionID)
                        $("#nombreInstitucion").val(data[i].name);
                        $("#direccionInstitucion").val(data[i].direction);
                        $("#telefonoInstitucion").val(data[i].phone);
                        $("#nivelEdInstitucion").val(data[i].educationLevelID);
                        $("#directorInstitucion").val(data[i].director);

                        //$("#ImgCarga").attr("src", "data:text/plain;base64," + data[i].photo);
                    }


                }).fail(function (jqXHR, textStatus, err) {

                    console.log(textStatus);
                    console.log(jqXHR);
                    console.log(err);


                });


                function actualizar() {
                    var nombre = $("#nombreInstitucion").val();
                    var direccion = $("#direccionInstitucion").val();
                    var telefono = $("#telefonoInstitucion").val();
                    var nivel = $("#nivelEdInstitucion").val();
                    var director = $("#directorInstitucion").val();

                    var ids = localStorage.getItem("inst");

                    alert(ids+" "+nombre + "" + direccion + "" + telefono + "" + nivel + "" + director);

                    if (nombre == "") {

                        swal("Ingresa todos los campos.");
                        $('#nombreInstitucion').focus();


                    } else if (direccion == "") {

                        swal("Ingresa todos los campos.");
                        $('#direccionInstitucion').focus();

                    } else if (telefono == "") {
                        swal("Ingresa todos los campos.");
                        $('#telefonoInstitucion').focus();

                    } else if (nivel == "Seleccionar") {
                        swal("Selecciona un nivel educativo.");
                        $('#nivelEdInstitucion').focus();


                    } else if (director == "") {
                        swal("Ingresa todos los campos.");
                        $('#directorInstitucion').focus();

                    } else {


                        var oModel = {

                            "institutionID" : ids,
                            "Name": nombre,
                            "Direction": direccion,
                            "Phone": telefono,
                            "EducationLevelID": nivel,
                            "Logo": "",
                            "Director": director,
                            "User": dateuser

                        }


                        $.ajax({

                            "async": true,
                            "crossDomain": true,
                            "cache": false,
                            "method": "POST",
                            "url": "http://localhost:59538/Api/Institution/UpdateRegister",
                            "data": JSON.stringify(oModel),
                            "contentType": "application/json"


                        }).done(function (data) {

                            alert(data.access_token);
                            error = "Ninguno";
                            msj = "Funcionamiento correcto";
                            accion = "Actualizacion de una institucion";
                            Information(accion, error, msj);
                            //alert("" + data);


                            swal("Institución actualizada", "La institución se actualizo correctamente", "success");
                            // $("#nombreGrupo").val("");
                            //$("#nombreGrupo").focus();
                            window.location.href = "/Institutions/ShowInstitution";
                            return false;


                            }).fail(function (jqXHR, textStatus, err) {
                                swal("Existio un problema al actualizar");
                                error = err + " " + textStatus + " " + jqXHR;
                                msj = "Administrador revisa el funcionamiento del portal";
                                accion = "Fallo actualizacion de una institucion";
                                Information(accion, error, msj);
                                console.log(textStatus)
                                window.location.href = "/Institutions/ShowInstitution";
                                return false


                        });
                    }
                }

            function Information(accion, error, msj) {
                var oModel = {
                    "Accion": accion,
                    "Error": error,
                    "Msj": msj
                }
                $.ajax({
                    "async": true,
                    "crossDomain": true,
                    "cache": false,
                    "method": "POST",
                    "url": "http://localhost:59538/Api/Binnacle/Info",
                    "data": JSON.stringify(oModel),
                    "contentType": "application/json"
                }).done(function (response) {
                    console.log(response);
                }).fail(function (jqXHR, textStatus, err) {
                    console.log(textStatus);
                });
            }
        </script>

ApptecPortalWeb/Views/InstitutoRegister/RegisterInstituto.cshtml
@{
    Layout = "~/Views/Shared/_InstitutoRegister.cshtml";
    ViewBag.Title = "Registrar";
}

@using (Html.BeginForm("CreateProfile", "Profile", FormMethod.Post))
{
    <center><h4 class="card-title">Registro de la Institución</h4></center>
    <br>
    <div class="form-group">
        <label class="label">Nombre</label>
        <div class="col-md-12">
            <div class="form-group">
                <label>Nombre</label>
                <input type="text" class="form-control" id="nombreAdmin" placeholder="Nombre" value="" required>
            </div>
        </div>
    </div>
    <div class="form-group">
        <label class="label">Dirección</label>
        <div class="col-md-12">
            <div class="form-group">
                <label>Direcci&oacute;n</label>
                <input type="text" class="form-control" id="direccion" placeholder="Direcci&oacute;n" value="" required>
            </div>
        </div>
    </div>
    <div class="form-group">
        <label class="label">Tel&eacute;fono</label>
        <div class="col-md-12">
            <div class="form-group">
                <label>Tel&eacute;fono</label>
                <input type="text" class="form-control" id="telefono" placeholder="Teléfono" value="" required>
            </div>
        </div>
    </div>

    <div class="col-md-12">
        <label class="label">Nivel Educativos</label>
        <div class="form-group">
            <label>Nivel educativo</label>
            <select class="form-control" id="nivelEdInstitucion" required>
                <option selected id="tomar">Seleccionar</option>
            </select>
        </div>

    </div>


    <div class="col-md-12">
        <label class="label">Director</label>
        <div class="form-group">
            <label>Director</label>
            <input type="text" class="form-control" id="directorInstitucion" placeholder="Nombre completo del director" value="" required>
        </div>
    </div>
    <br>
    <div class="form-group">
        <label class="label">Tel&eacute;fono</label>
        <center>
            <button type="button" onclick="Registrar()" class="btn btn-primary submit-btn btn-block">Registrar</button>
        </center>
    </div>

    <script type="text/javascript" src="~/Scripts/jquery-3.4.1.js"></script>

    <script src="~/Scripts/Platform/Institution/GetEducationLevel.js"></script>
    <script src="~/Scripts/Platform/Institution/RegisterInstituto.js"></script>

}

ApptecPortalWeb/Views/Login/Login.cshtml
@{
    Layout = "~/Views/Shared/_Login.cshtml";
    ViewBag.Title = "Login";
}

@using (Html.BeginForm("", "", FormMethod.Post))
{
    <div class="form-group">
        <label>Username</label>
        <input type="text" class="form-control" id="user" placeholder="Usuario" required>
    </div>
    <div class="form-group">
        <label>Password</label>
        <input type="password" class="form-control" id="pass" name="password" data-toggle="password" placeholder="Contraseña" required>
    </div>
    <br>
    <div class="form-group">
        <button type="button" class="btn btn-primary submit-btn btn-block" onclick="logear()">Entrar</button>
    </div>
    <br>
    <div class="text-block text-center my-3">
        <span class="text-small font-weight-semibold">
            ¿A&uacute;n no eres miembro?
            @Html.ActionLink("Crea una cuenta aqui", "RegisterInstituto", "InstitutoRegister", new { area = "" }, new { @class = "nav-link" })
        </span>
    </div>
}

<script type="text/javascript" src="~/Scripts/jquery-3.4.1.js"></script>

<script src="~/Scripts/Platform/Login/Login.js"></script>